begin;
select plan(31);

select has_function('app_private','run_notice_publication_job',array['uuid','integer'],'guarded worker entrypoint exists');
select has_function('app_private','dispatch_notice_publication_worker',array[]::text[],'cron dispatcher exists');
select has_function('public','claim_notice_publication_jobs_for_worker',array['text','integer'],'PostgREST claim wrapper exists');
select has_function('public','run_notice_publication_job_for_worker',array['uuid','integer'],'PostgREST run wrapper exists');
select ok(not has_function_privilege('authenticated','app_private.run_notice_publication_job(uuid,int)','execute'),'frontend cannot run publication jobs');
select ok(has_function_privilege('service_role','app_private.run_notice_publication_job(uuid,int)','execute'),'service role can run publication jobs');
select ok(not has_function_privilege('authenticated','public.run_notice_publication_job_for_worker(uuid,int)','execute'),'frontend cannot use worker wrapper');
select ok(has_function_privilege('service_role','public.run_notice_publication_job_for_worker(uuid,int)','execute'),'service role can use worker wrapper');
select ok(not has_schema_privilege('service_role','app_private','usage'),'service role stays outside the private schema');
select ok(position('lease_expired' in pg_get_functiondef('app_private.claim_notice_publication_jobs(text,int)'::regprocedure))>0,'stale leases are recoverable');
select ok(position('for update skip locked' in lower(pg_get_functiondef('app_private.claim_notice_publication_jobs(text,int)'::regprocedure)))>0,'claims remain concurrent-safe');
select ok(position('notice.management_version <> job.notice_version' in pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure))>0,'superseded jobs fail closed');
select ok(position($needle$notice.status::text <> 'scheduled'$needle$ in pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure))>0,'paused or inactive notices cannot materialize');
select ok(position('materialize_notice_publication_job' in pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure))>0,'valid jobs use the bounded materializer');
select is((select count(*)::integer from cron.job where jobname='coelo-notice-publication-worker'),1,'worker cron is versioned exactly once');
select ok(position('notice_publication_worker_secret' in pg_get_functiondef('app_private.dispatch_notice_publication_worker()'::regprocedure))>0,'dispatcher reads an opaque Vault secret');
select ok(position('delivered_at = null' in lower(pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure)))>0,'materialization explicitly preserves delivery as pending');
select has_column('public','platform_notices','current_publication_job_id','notice tracks its current publication');
select has_column('public','notice_receipts','publication_job_id','receipt belongs to one publication job');
select has_column('public','notice_receipts','notice_version','receipt records the frozen notice version');
select has_column('public','notice_receipts','materialized_at','receipt records audience materialization separately from delivery');
select has_column('public','notice_receipts','delivery_state','receipt has an explicit real-delivery state');
select fk_ok('public','notice_receipts','publication_job_id','app_private','notice_publication_jobs','id','receipt job is referentially protected');
select index_is_unique('public','notice_receipts','notice_receipts_job_institution_uidx','institution-scoped recipients are unique per publication');
select index_is_unique('public','notice_receipts','notice_receipts_job_platform_uidx','platform recipients are unique per publication');
select ok(position('notice.ends_at <= now()' in pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure))>0,'expired notices fail closed before materialization');
select ok(position('publication_job_id' in pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure))>0,'worker versions newly materialized receipts');
select ok(position('materialized_at >= materialization_started_at' in pg_get_functiondef('app_private.run_notice_publication_job(uuid,int)'::regprocedure))>0,'worker never adopts unversioned legacy receipts');
select ok(position('current_publication_job_id' in pg_get_functiondef('public.get_notice_for_superadmin(uuid)'::regprocedure))>0,'detail metrics use only the current publication');
select ok(position('current_publication_job_id' in pg_get_functiondef('public.list_notices_for_superadmin(text[],text,text[],text[],timestamptz,uuid,int)'::regprocedure))>0,'typed directory metrics use only the current publication');
select col_is_null('public','notice_receipts','delivered_at','audience materialization never implies delivery');

select * from finish();
rollback;
