begin;
create extension if not exists pgtap with schema extensions;
select plan(30);
select has_table('public','now_publications','Agora publications exist');
select has_table('public','now_publication_audiences','Agora audiences exist');
select has_table('public','now_media_assets','Agora private asset metadata exists');
select has_table('app_private','now_publication_audit','Agora audit exists');
select has_function('public','load_now_draft',array['uuid','uuid','uuid'],'draft query exists');
select has_function('public','save_now_draft',array['uuid','jsonb','uuid','bigint'],'draft command exists');
select has_function('public','prepare_now_asset_upload',array['uuid','uuid','now_asset_kind','text','text','bigint','numeric','boolean'],'upload preparation exists');
select has_function('public','finalize_now_asset_upload',array['uuid','text'],'upload finalization exists');
select has_function('public','publish_now',array['uuid','uuid','bigint','timestamp with time zone'],'publish command exists');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.now_publications'::regclass),'publications force RLS');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.now_publication_audiences'::regclass),'audiences force RLS');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.now_media_assets'::regclass),'assets force RLS');
select ok(not has_table_privilege('authenticated','public.now_publications','insert,update,delete'),'client cannot mutate publications directly');
select ok(not has_table_privilege('authenticated','public.now_media_assets','insert,update,delete'),'client cannot mutate assets directly');
select ok(exists(select 1 from storage.buckets where id='coelo-now-mvp' and not public),'Agora bucket is private');
select ok(not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname like 'now_%'),'browser has no direct storage policy');
select ok(position('now.publications.create' in pg_get_functiondef('public.save_now_draft(uuid,jsonb,uuid,bigint)'::regprocedure))>0,'save checks capability');
select ok(position('now.publications.publish' in pg_get_functiondef('public.publish_now(uuid,uuid,bigint,timestamptz)'::regprocedure))>0,'publish checks capability');
select ok(position('expected_version' in pg_get_functiondef('public.save_now_draft(uuid,jsonb,uuid,bigint)'::regprocedure))>0,'save uses optimistic version');
select ok(position('video_duration_exceeded' in pg_get_functiondef('public.prepare_now_asset_upload(uuid,uuid,public.now_asset_kind,text,text,bigint,numeric,boolean)'::regprocedure))>0,'backend validates video duration');
select ok(position('audio_rights_required' in pg_get_functiondef('public.prepare_now_asset_upload(uuid,uuid,public.now_asset_kind,text,text,bigint,numeric,boolean)'::regprocedure))>0,'backend requires audio rights');
select ok(position('24 hours' in pg_get_functiondef('public.publish_now(uuid,uuid,bigint,timestamptz)'::regprocedure))>0,'publication expires after 24 hours');
select ok(exists(select 1 from pg_indexes where schemaname='app_private' and indexname='now_publication_audit_idempotency_idx'),'commands have durable idempotency key');
select ok(position('request_id=p_request_id' in replace(pg_get_functiondef('public.save_now_draft(uuid,jsonb,uuid,bigint)'::regprocedure),' ',''))>0,'draft save replays idempotent response');
select ok(position('target.unit_id,target.group_id' in replace(pg_get_functiondef('public.prepare_now_asset_upload(uuid,uuid,public.now_asset_kind,text,text,bigint,numeric,boolean)'::regprocedure),' ',''))>0,'asset upload checks publication context');
select ok(position('26214400' in pg_get_functiondef('public.prepare_now_asset_upload(uuid,uuid,public.now_asset_kind,text,text,bigint,numeric,boolean)'::regprocedure))>0,'asset byte size is bounded server-side');
select ok(position('public.units' in pg_get_functiondef('app_private.now_actor(uuid,text,uuid,uuid)'::regprocedure))>0,'unit context is checked against institution');
select ok(position('public.groups' in pg_get_functiondef('app_private.now_actor(uuid,text,uuid,uuid)'::regprocedure))>0,'group context is checked against institution and unit');
select ok(position('unsupported_cover_type' in pg_get_functiondef('public.prepare_now_asset_upload(uuid,uuid,public.now_asset_kind,text,text,bigint,numeric,boolean)'::regprocedure))>0,'cover accepts image MIME types only');
select ok(position('p_kind::text' in pg_get_functiondef('public.prepare_now_asset_upload(uuid,uuid,public.now_asset_kind,text,text,bigint,numeric,boolean)'::regprocedure))>0,'asset replacement uses deterministic object key without orphaning prior storage');
select * from finish();
rollback;
