begin;
select plan(18);
select has_table('public','agenda_events','agenda events exist');
select has_table('public','agenda_publication_requests','publication requests exist');
select has_table('public','agenda_guardian_requests','guardian requests exist');
select has_table('public','agenda_responses','responses exist');
select has_table('public','agenda_history_receipts','history receipts exist');
select row_security_active('public.agenda_events'::regclass,'events RLS active');
select row_security_active('public.agenda_publication_requests'::regclass,'publication RLS active');
select row_security_active('public.agenda_guardian_requests'::regclass,'guardian RLS active');
select row_security_active('public.agenda_responses'::regclass,'responses RLS active');
select row_security_active('public.agenda_history_receipts'::regclass,'history RLS active');
select is(has_table_privilege('anon','public.agenda_events','select'),false,'anon cannot read agenda');
select is(has_table_privilege('authenticated','public.agenda_events','select'),false,'authenticated cannot read tables directly');
select is(has_table_privilege('authenticated','public.agenda_events','insert'),false,'authenticated cannot write tables directly');
select function_returns('public','superadmin_agenda_list',array['timestamp with time zone','timestamp with time zone','uuid','text','integer','integer'],'jsonb','list RPC');
select function_returns('public','superadmin_agenda_get',array['uuid'],'jsonb','get RPC');
select function_returns('public','superadmin_agenda_save',array['uuid','uuid','bigint','jsonb','text','boolean'],'jsonb','save RPC');
select function_returns('public','superadmin_agenda_command',array['uuid','uuid','bigint','text','text'],'jsonb','command RPC');
select function_returns('public','superadmin_agenda_requests',array['text','text','integer','integer'],'jsonb','requests RPC');
select * from finish();
rollback;
