-- C02 I013. Response images only; authoring and upload remain separate gates.
-- The timestamp was generated by the coordinator's Supabase CLI.
begin;

create table app_private.form_media_read_tokens (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  asset_id uuid not null references public.form_assets(id) on delete restrict,
  media_asset_id uuid not null references public.media_assets(id) on delete restrict,
  response_id uuid not null references public.form_responses(id) on delete restrict,
  institution_id uuid not null references public.institutions(id) on delete restrict,
  form_id uuid not null references public.forms(id) on delete restrict,
  form_version_id uuid not null references public.form_versions(id) on delete restrict,
  item_id uuid not null references public.form_items(id) on delete restrict,
  rendition text not null check (rendition in ('original','preview')),
  actor_internal_identity_id uuid not null references app_private.superadmin_internal_identities(id) on delete restrict,
  actor_auth_link_id uuid not null references app_private.superadmin_internal_auth_links(id) on delete restrict,
  actor_membership_id uuid not null references app_private.superadmin_internal_memberships(id) on delete restrict,
  actor_auth_session_id uuid not null,
  actor_scope_kind text not null check (actor_scope_kind in ('platform','institution')),
  actor_scope_institution_id uuid references public.institutions(id) on delete restrict,
  actor_aal text not null check (actor_aal in ('aal1','aal2')),
  created_at timestamptz not null default clock_timestamp(),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  check (expires_at>created_at and expires_at<=created_at+interval '2 minutes'),
  check (((actor_scope_kind='platform' and actor_scope_institution_id is null)
    or (actor_scope_kind='institution' and actor_scope_institution_id=institution_id)) is true),
  check (consumed_at is null or consumed_at>=created_at)
);
alter table app_private.form_media_read_tokens enable row level security;
alter table app_private.form_media_read_tokens force row level security;
revoke all on app_private.form_media_read_tokens from public,anon,authenticated,service_role;
create index form_media_read_tokens_asset_idx on app_private.form_media_read_tokens(asset_id);
create index form_media_read_tokens_catalog_idx on app_private.form_media_read_tokens(media_asset_id);
create index form_media_read_tokens_response_idx on app_private.form_media_read_tokens(response_id);
create index form_media_read_tokens_institution_idx on app_private.form_media_read_tokens(institution_id);
create index form_media_read_tokens_form_idx on app_private.form_media_read_tokens(form_id);
create index form_media_read_tokens_version_idx on app_private.form_media_read_tokens(form_version_id);
create index form_media_read_tokens_item_idx on app_private.form_media_read_tokens(item_id);
create index form_media_read_tokens_identity_idx on app_private.form_media_read_tokens(actor_internal_identity_id);
create index form_media_read_tokens_link_idx on app_private.form_media_read_tokens(actor_auth_link_id);
create index form_media_read_tokens_membership_idx on app_private.form_media_read_tokens(actor_membership_id);
create index form_media_read_tokens_scope_idx on app_private.form_media_read_tokens(actor_scope_institution_id);
create index form_media_read_tokens_session_idx on app_private.form_media_read_tokens(actor_auth_session_id);
create index form_media_read_tokens_expiry_idx on app_private.form_media_read_tokens(expires_at) where consumed_at is null;

create function app_private.forms_media_read_token_immutable_v1() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  if (to_jsonb(new)-'consumed_at') is distinct from (to_jsonb(old)-'consumed_at')
    or old.consumed_at is not null or new.consumed_at is null then
    raise check_violation using message='forms_media_read_token_immutable';
  end if;
  return new;
end;
$$;
create trigger forms_media_read_token_immutable_v1 before update on app_private.form_media_read_tokens
  for each row execute function app_private.forms_media_read_token_immutable_v1();

-- Same session reconstruction pattern as XLSX, with this operation's own
-- capability. Never call the XLSX helper or create a global People identity.
create function app_private.forms_media_read_context_v1(
  p_identity uuid,p_link uuid,p_membership uuid,p_session uuid,p_scope text,p_institution uuid
) returns app_private.superadmin_internal_context
language plpgsql volatile security definer set search_path='' as $$
declare ctx app_private.superadmin_internal_context; v_auth_user_id uuid; session_aal text;
  original_claims text:=current_setting('request.jwt.claims',true);
  original_sub text:=current_setting('request.jwt.claim.sub',true);
begin
  select s.user_id,s.aal::text into v_auth_user_id,session_aal from auth.sessions s
    where s.id=p_session and (s.not_after is null or s.not_after>clock_timestamp());
  if v_auth_user_id is null or session_aal is null or session_aal not in ('aal1','aal2') then
    raise insufficient_privilege using detail='SAI_SESSION_INVALID';
  end if;
  perform set_config('request.jwt.claims',jsonb_build_object('sub',v_auth_user_id,'session_id',p_session,
    'aal',session_aal,'role','authenticated')::text,true);
  perform set_config('request.jwt.claim.sub',v_auth_user_id::text,true);
  select * into strict ctx from app_private.require_superadmin_internal_context('forms.responses.read');
  if row(ctx.internal_identity_id,ctx.internal_auth_link_id,ctx.internal_membership_id,ctx.session_id,
    ctx.scope_kind,ctx.scope_institution_id) is distinct from row(p_identity,p_link,p_membership,p_session,p_scope,p_institution)
    or ctx.scope_kind is null or ctx.scope_kind not in ('platform','institution')
    or (ctx.scope_kind='institution' and ctx.scope_institution_id is null)
    or not exists(select 1 from auth.sessions s where s.id=p_session and s.user_id=v_auth_user_id
      and (s.not_after is null or s.not_after>clock_timestamp())) then
    raise insufficient_privilege using detail='SAI_INTERNAL_CONTEXT_DENIED';
  end if;
  perform set_config('request.jwt.claims',coalesce(original_claims,''),true);
  perform set_config('request.jwt.claim.sub',coalesce(original_sub,''),true);
  return ctx;
exception when others then
  perform set_config('request.jwt.claims',coalesce(original_claims,''),true);
  perform set_config('request.jwt.claim.sub',coalesce(original_sub,''),true);
  raise;
end;
$$;

-- Issue and redeem share the same locked chain. Bind a token to one actual
-- submitted response; another attachment cannot silently replace it later.
create function app_private.forms_answer_media_descriptor_v1(
  p_asset uuid,p_rendition text,p_scope text,p_institution uuid,p_response uuid default null
) returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare v_response_id uuid; result jsonb;
begin
  if p_asset is null or p_rendition not in ('original','preview') or p_rendition is null
    or p_scope is null or p_scope not in ('platform','institution')
    or (p_scope='institution' and p_institution is null) then
    raise insufficient_privilege using detail='SAI_PERMISSION_DENIED';
  end if;
  select r.id into v_response_id
    from public.form_assets source
    join public.form_answer_assets attachment on attachment.asset_id=source.id
    join public.form_answers answer on answer.id=attachment.answer_id
    join public.form_responses r on r.id=answer.response_id
    where source.id=p_asset and r.status='submitted'
      and (p_response is null or r.id=p_response)
      and r.institution_id=source.institution_id and r.occurrence_id=source.occurrence_id
      and (p_scope='platform' or r.institution_id=p_institution)
    order by r.id limit 1 for share of r;
  if v_response_id is null then raise insufficient_privilege using detail='SAI_PERMISSION_DENIED'; end if;
  -- This final join, after the response lock, rechecks all relationships and
  -- locks attachment/definition/catalog rows against concurrent revocation.
  select jsonb_build_object('asset_id',source.id,'media_asset_id',asset.id,'response_id',r.id,
      'institution_id',f.institution_id,'form_id',f.id,'form_version_id',v.id,'item_id',item.id,
      'rendition',variant.rendition,'bucket',variant.bucket_id,'object_key',variant.object_key,'mime_type',variant.mime_type)
    into result
    from public.form_assets source
    join public.form_answer_assets attachment on attachment.asset_id=source.id
    join public.form_answers answer on answer.id=attachment.answer_id and answer.item_id=source.item_id
    join public.form_responses r on r.id=answer.response_id and r.id=v_response_id
    join public.form_occurrences occurrence on occurrence.id=r.occurrence_id and occurrence.id=source.occurrence_id
      and occurrence.institution_id=r.institution_id and occurrence.form_id=r.form_id
      and occurrence.form_version_id=r.form_version_id
    join public.forms f on f.id=r.form_id and f.institution_id=r.institution_id
    join public.institutions institution on institution.id=f.institution_id and institution.deleted_at is null
    join public.form_versions v on v.id=r.form_version_id and v.form_id=f.id
    join public.form_items item on item.id=source.item_id and item.form_version_id=v.id
    join public.form_sections section on section.id=item.section_id and section.form_version_id=v.id
    join public.media_assets asset on asset.source_form_asset_id=source.id and asset.form_id=f.id
      and asset.institution_id=f.institution_id and asset.catalog_kind='form-image'
      and asset.media_purpose='answer-image' and asset.status='ready'
    join public.media_bindings binding on binding.media_asset_id=asset.id and binding.item_id=item.id
      and binding.form_version_id=v.id and binding.purpose='answer-image'
    join public.media_variants variant on variant.media_asset_id=asset.id and variant.rendition=p_rendition
    where source.id=p_asset and source.state='finalized' and source.institution_id=f.institution_id
      and r.status='submitted' and r.identity_mode=f.identity_mode
      and answer.form_version_id=v.id and answer.answer_kind=item.kind and item.kind in ('photo','gallery')
      and asset.owner_person_id is not distinct from source.prepared_by_person_id
      and ((source.prepared_by_person_id is null)=(f.identity_mode='anonymous'))
      and (r.identity_mode='anonymous' or source.prepared_by_person_id=r.respondent_person_id)
      and (p_scope='platform' or f.institution_id=p_institution)
      and variant.bucket_id='coelo-media-prod'
      and app_private.private_media_catalog_key_v1(asset,p_rendition,variant.object_key,variant.mime_type) is true
    order by answer.id limit 1
    for share of source,attachment,answer,r,occurrence,f,institution,v,item,section,asset,binding,variant;
  if result is null then raise insufficient_privilege using detail='SAI_PERMISSION_DENIED'; end if;
  return result;
end;
$$;

create function app_private.superadmin_form_authorize_media_read_v2(p_query jsonb)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare ctx app_private.superadmin_internal_context; initial_ctx app_private.superadmin_internal_context;
  asset_id uuid; rendition text; descriptor jsonb; raw_token uuid:=gen_random_uuid();
  issued_at timestamptz; token_expiry timestamptz; error_code text; correlation uuid:=gen_random_uuid();
begin
  begin
    select * into strict ctx from app_private.require_superadmin_internal_context('forms.responses.read');
    initial_ctx:=ctx;
    if current_setting('transaction_isolation')<>'read committed' or jsonb_typeof(p_query) is distinct from 'object'
      or octet_length(p_query::text)>32768 or p_query-array['asset_id','rendition']<>'{}'::jsonb
      or jsonb_typeof(p_query->'asset_id') is distinct from 'string'
      or p_query->>'asset_id' !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      or jsonb_typeof(p_query->'rendition') is distinct from 'string'
      or p_query->>'rendition' not in ('original','preview') then
      raise invalid_parameter_value using detail='SAI_INVALID_ARGUMENT';
    end if;
    if ctx.aal is null or ctx.aal not in ('aal1','aal2') or ctx.scope_kind is null
      or ctx.scope_kind not in ('platform','institution')
      or (ctx.scope_kind='institution' and ctx.scope_institution_id is null) then
      raise insufficient_privilege using detail='SAI_INTERNAL_CONTEXT_DENIED';
    end if;
    asset_id:=(p_query->>'asset_id')::uuid; rendition:=p_query->>'rendition';
    descriptor:=app_private.forms_answer_media_descriptor_v1(asset_id,rendition,ctx.scope_kind,ctx.scope_institution_id);
    select * into strict ctx from app_private.require_superadmin_internal_context('forms.responses.read');
    if row(ctx.internal_identity_id,ctx.internal_auth_link_id,ctx.internal_membership_id,ctx.session_id,ctx.scope_kind,ctx.scope_institution_id)
      is distinct from row(initial_ctx.internal_identity_id,initial_ctx.internal_auth_link_id,initial_ctx.internal_membership_id,
        initial_ctx.session_id,initial_ctx.scope_kind,initial_ctx.scope_institution_id)
      or not exists(select 1 from auth.sessions s where s.id=ctx.session_id and s.user_id=ctx.auth_user_id
        and (s.not_after is null or s.not_after>clock_timestamp())) then
      raise insufficient_privilege using detail='SAI_INTERNAL_CONTEXT_DENIED';
    end if;
    issued_at:=clock_timestamp(); token_expiry:=issued_at+interval '2 minutes';
    insert into app_private.form_media_read_tokens(token_hash,asset_id,media_asset_id,response_id,institution_id,
      form_id,form_version_id,item_id,rendition,actor_internal_identity_id,actor_auth_link_id,actor_membership_id,
      actor_auth_session_id,actor_scope_kind,actor_scope_institution_id,actor_aal,created_at,expires_at)
    values(encode(extensions.digest(convert_to(raw_token::text,'UTF8'),'sha256'),'hex'),asset_id,
      (descriptor->>'media_asset_id')::uuid,(descriptor->>'response_id')::uuid,(descriptor->>'institution_id')::uuid,
      (descriptor->>'form_id')::uuid,(descriptor->>'form_version_id')::uuid,(descriptor->>'item_id')::uuid,rendition,
      ctx.internal_identity_id,ctx.internal_auth_link_id,ctx.internal_membership_id,ctx.session_id,
      ctx.scope_kind,ctx.scope_institution_id,ctx.aal,issued_at,token_expiry);
  exception when others then
    get stacked diagnostics error_code=pg_exception_detail;
    error_code:=app_private.superadmin_internal_error_envelope(error_code,correlation)#>>'{error,code}';
  end;
  if error_code is not null then
    perform app_private.audit_superadmin_internal_denial_if_identified('forms.responses.read',
      'superadmin.forms.media.read.authorize',error_code,correlation);
    return app_private.superadmin_internal_error_envelope(error_code,correlation);
  end if;
  -- Outside the recoverable block: failed audit rolls the ticket back.
  perform app_private.audit_append_superadmin_internal(ctx.internal_identity_id,ctx.internal_auth_link_id,ctx.internal_membership_id,
    ctx.session_id,'forms.responses.read',ctx.aal,'superadmin.forms.media.read.authorize','success',null,
    correlation,(descriptor->>'institution_id')::uuid,'form_asset',asset_id);
  return jsonb_build_object('ok',true,'error',null,'data',jsonb_build_object(
    'asset_id',asset_id,'rendition',rendition,'read_token',raw_token,'expires_at',token_expiry));
end;
$$;

create function app_private.form_redeem_media_read_r2_v1(p_read_token text)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare token_row app_private.form_media_read_tokens; descriptor jsonb;
  ctx app_private.superadmin_internal_context; token_digest text; error_code text;
  correlation uuid:=gen_random_uuid();
begin
  if current_setting('transaction_isolation')<>'read committed' then
    raise invalid_parameter_value using message='forms_media_read_isolation_invalid';
  end if;
  if p_read_token is null or p_read_token !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then return null; end if;
  token_digest:=encode(extensions.digest(convert_to(lower(p_read_token),'UTF8'),'sha256'),'hex');
  -- Consume before the recoverable authorization block. Denial never revives
  -- the capability; concurrent replay waits and then sees no unconsumed row.
  update app_private.form_media_read_tokens set consumed_at=clock_timestamp()
    where token_hash=token_digest and consumed_at is null returning * into token_row;
  if token_row.id is null then return null; end if;
  begin
    if token_row.expires_at<=clock_timestamp() then raise insufficient_privilege using detail='SAI_PERMISSION_DENIED'; end if;
    ctx:=app_private.forms_media_read_context_v1(token_row.actor_internal_identity_id,token_row.actor_auth_link_id,
      token_row.actor_membership_id,token_row.actor_auth_session_id,token_row.actor_scope_kind,token_row.actor_scope_institution_id);
    descriptor:=app_private.forms_answer_media_descriptor_v1(token_row.asset_id,token_row.rendition,
      ctx.scope_kind,ctx.scope_institution_id,token_row.response_id);
    if row((descriptor->>'asset_id')::uuid,(descriptor->>'media_asset_id')::uuid,(descriptor->>'response_id')::uuid,
      (descriptor->>'institution_id')::uuid,(descriptor->>'form_id')::uuid,(descriptor->>'form_version_id')::uuid,(descriptor->>'item_id')::uuid)
      is distinct from row(token_row.asset_id,token_row.media_asset_id,token_row.response_id,token_row.institution_id,
        token_row.form_id,token_row.form_version_id,token_row.item_id) then
      raise insufficient_privilege using detail='SAI_PERMISSION_DENIED';
    end if;
    ctx:=app_private.forms_media_read_context_v1(token_row.actor_internal_identity_id,token_row.actor_auth_link_id,
      token_row.actor_membership_id,token_row.actor_auth_session_id,token_row.actor_scope_kind,token_row.actor_scope_institution_id);
    if token_row.expires_at<=clock_timestamp() then raise insufficient_privilege using detail='SAI_PERMISSION_DENIED'; end if;
  exception when others then
    get stacked diagnostics error_code=pg_exception_detail;
    error_code:=app_private.superadmin_internal_error_envelope(error_code,correlation)#>>'{error,code}';
  end;
  -- Outside the catch: denial consumption and its audit commit together.
  perform app_private.audit_append_superadmin_internal(token_row.actor_internal_identity_id,token_row.actor_auth_link_id,
    token_row.actor_membership_id,token_row.actor_auth_session_id,'forms.responses.read',token_row.actor_aal,
    'superadmin.forms.media.read.redeem',case when error_code is null then 'success'::public.audit_outcome else 'denied'::public.audit_outcome end,
    error_code,correlation,token_row.institution_id,'form_asset',token_row.asset_id);
  if error_code is not null then return null; end if;
  return (descriptor-array['response_id','form_version_id','item_id'])||jsonb_build_object('expires_at',token_row.expires_at);
end;
$$;

create function public.superadmin_form_authorize_media_read_v2(p_query jsonb) returns jsonb
language sql volatile security definer set search_path='' as $$
  select app_private.superadmin_form_authorize_media_read_v2($1);
$$;
create function public.form_redeem_media_read_r2_v1(p_read_token text) returns jsonb
language sql volatile security definer set search_path='' as $$
  select app_private.form_redeem_media_read_r2_v1($1);
$$;
revoke all on function app_private.forms_media_read_token_immutable_v1(),
  app_private.forms_media_read_context_v1(uuid,uuid,uuid,uuid,text,uuid),
  app_private.forms_answer_media_descriptor_v1(uuid,text,text,uuid,uuid),
  app_private.superadmin_form_authorize_media_read_v2(jsonb),app_private.form_redeem_media_read_r2_v1(text)
  from public,anon,authenticated,service_role;
revoke all on function public.superadmin_form_authorize_media_read_v2(jsonb) from public,anon,service_role;
revoke all on function public.form_redeem_media_read_r2_v1(text) from public,anon,authenticated;
grant execute on function public.superadmin_form_authorize_media_read_v2(jsonb) to authenticated;
grant execute on function public.form_redeem_media_read_r2_v1(text) to service_role;
comment on table app_private.form_media_read_tokens is 'I013 short one-use hashed image read capabilities; no upload expiry or reader ownership inferred from form_assets.';
commit;
