-- Contextual Activities foundation.
-- Sources: decisions/0014-contextual-activities-and-delegated-unit-creation.md;
-- specs/014-atividade-contextual.md; specs/011-superadmin-database-rls.md.
-- Timestamp generated by Supabase CLI 2.109.1 (`supabase migration new`).

do $$
begin
  create type public.activity_origin_scope as enum ('institution', 'unit');
exception when duplicate_object then null;
end
$$;

do $$
begin
  create type public.activity_permission_scope as enum ('institution', 'unit');
exception when duplicate_object then null;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.units'::regclass
      and conname = 'units_id_institution_key'
  ) then
    alter table public.units
      add constraint units_id_institution_key unique (id, institution_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.groups'::regclass
      and conname = 'groups_id_institution_unit_key'
  ) then
    alter table public.groups
      add constraint groups_id_institution_unit_key
      unique (id, institution_id, unit_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.institution_memberships'::regclass
      and conname = 'institution_memberships_id_institution_person_key'
  ) then
    alter table public.institution_memberships
      add constraint institution_memberships_id_institution_person_key
      unique (id, institution_id, person_id);
  end if;
end
$$;

create table public.activity_capabilities (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  name text not null,
  description text,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_capabilities_code_not_blank check (btrim(code) <> ''),
  constraint activity_capabilities_name_not_blank check (btrim(name) <> ''),
  constraint activity_capabilities_description_not_blank
    check (description is null or btrim(description) <> '')
);

create unique index activity_capabilities_code_uidx
  on public.activity_capabilities(lower(code));

create table public.activity_definitions (
  id uuid primary key default gen_random_uuid(),
  institution_id uuid not null references public.institutions(id) on delete cascade,
  name text not null,
  description text,
  origin_scope_kind public.activity_origin_scope not null,
  origin_unit_id uuid,
  created_by_person_id uuid not null references public.people(id) on delete restrict,
  status public.record_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint activity_definitions_id_institution_key unique (id, institution_id),
  constraint activity_definitions_name_not_blank check (btrim(name) <> ''),
  constraint activity_definitions_description_not_blank
    check (description is null or btrim(description) <> ''),
  constraint activity_definitions_origin_check check (
    (origin_scope_kind = 'institution' and origin_unit_id is null)
    or (origin_scope_kind = 'unit' and origin_unit_id is not null)
  ),
  constraint activity_definitions_archive_check check (
    (status = 'archived' and archived_at is not null)
    or (status <> 'archived' and archived_at is null)
  ),
  constraint activity_definitions_origin_unit_fkey
    foreign key (origin_unit_id, institution_id)
    references public.units(id, institution_id)
    on delete restrict
);

create unique index activity_definitions_active_name_uidx
  on public.activity_definitions(institution_id, lower(name))
  where status <> 'archived';
create index activity_definitions_institution_status_idx
  on public.activity_definitions(institution_id, status, created_at desc);
create index activity_definitions_origin_unit_idx
  on public.activity_definitions(origin_unit_id)
  where origin_unit_id is not null;
create index activity_definitions_created_by_idx
  on public.activity_definitions(created_by_person_id);

create table public.activity_unit_links (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid not null,
  institution_id uuid not null,
  unit_id uuid not null,
  linked_by_person_id uuid not null references public.people(id) on delete restrict,
  status public.record_status not null default 'active',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_unit_links_activity_unit_key
    unique (activity_id, unit_id),
  constraint activity_unit_links_activity_institution_unit_key
    unique (activity_id, institution_id, unit_id),
  constraint activity_unit_links_dates_check
    check (ends_at is null or ends_at > starts_at),
  constraint activity_unit_links_activity_fkey
    foreign key (activity_id, institution_id)
    references public.activity_definitions(id, institution_id)
    on delete cascade,
  constraint activity_unit_links_unit_fkey
    foreign key (unit_id, institution_id)
    references public.units(id, institution_id)
    on delete restrict
);

create index activity_unit_links_unit_status_idx
  on public.activity_unit_links(unit_id, status);
create index activity_unit_links_activity_status_idx
  on public.activity_unit_links(activity_id, status);
create index activity_unit_links_linked_by_idx
  on public.activity_unit_links(linked_by_person_id);

create table public.activity_permission_profiles (
  id uuid primary key default gen_random_uuid(),
  institution_id uuid not null references public.institutions(id) on delete cascade,
  scope_kind public.activity_permission_scope not null,
  unit_id uuid,
  code text not null,
  name text not null,
  description text,
  status public.record_status not null default 'active',
  created_by_person_id uuid not null references public.people(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint activity_permission_profiles_id_institution_key
    unique (id, institution_id),
  constraint activity_permission_profiles_scope_check check (
    (scope_kind = 'institution' and unit_id is null)
    or (scope_kind = 'unit' and unit_id is not null)
  ),
  constraint activity_permission_profiles_code_not_blank check (btrim(code) <> ''),
  constraint activity_permission_profiles_name_not_blank check (btrim(name) <> ''),
  constraint activity_permission_profiles_description_not_blank
    check (description is null or btrim(description) <> ''),
  constraint activity_permission_profiles_archive_check check (
    (status = 'archived' and archived_at is not null)
    or (status <> 'archived' and archived_at is null)
  ),
  constraint activity_permission_profiles_unit_fkey
    foreign key (unit_id, institution_id)
    references public.units(id, institution_id)
    on delete restrict
);

create unique index activity_permission_profiles_scope_code_uidx
  on public.activity_permission_profiles(
    institution_id,
    scope_kind,
    coalesce(unit_id, '00000000-0000-0000-0000-000000000000'::uuid),
    lower(code)
  )
  where status <> 'archived';
create index activity_permission_profiles_institution_status_idx
  on public.activity_permission_profiles(institution_id, status);
create index activity_permission_profiles_unit_idx
  on public.activity_permission_profiles(unit_id)
  where unit_id is not null;
create index activity_permission_profiles_created_by_idx
  on public.activity_permission_profiles(created_by_person_id);

create table public.activity_permission_profile_capabilities (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.activity_permission_profiles(id) on delete cascade,
  capability_id uuid not null references public.activity_capabilities(id) on delete restrict,
  effect public.permission_effect not null default 'allow',
  changed_by_person_id uuid not null references public.people(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (profile_id, capability_id)
);

create index activity_profile_capabilities_capability_idx
  on public.activity_permission_profile_capabilities(capability_id);
create index activity_profile_capabilities_changed_by_idx
  on public.activity_permission_profile_capabilities(changed_by_person_id);

create table public.activity_group_links (
  id uuid primary key default gen_random_uuid(),
  activity_id uuid not null,
  institution_id uuid not null,
  unit_id uuid not null,
  group_id uuid not null,
  permission_profile_id uuid,
  linked_by_person_id uuid not null references public.people(id) on delete restrict,
  status public.record_status not null default 'active',
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_group_links_id_institution_key unique (id, institution_id),
  constraint activity_group_links_activity_group_key unique (activity_id, group_id),
  constraint activity_group_links_dates_check
    check (ends_at is null or ends_at > starts_at),
  constraint activity_group_links_activity_unit_fkey
    foreign key (activity_id, institution_id, unit_id)
    references public.activity_unit_links(activity_id, institution_id, unit_id)
    on delete cascade,
  constraint activity_group_links_group_fkey
    foreign key (group_id, institution_id, unit_id)
    references public.groups(id, institution_id, unit_id)
    on delete restrict,
  constraint activity_group_links_profile_fkey
    foreign key (permission_profile_id, institution_id)
    references public.activity_permission_profiles(id, institution_id)
    on delete restrict
);

create index activity_group_links_activity_status_idx
  on public.activity_group_links(activity_id, status);
create index activity_group_links_group_status_idx
  on public.activity_group_links(group_id, status);
create index activity_group_links_unit_status_idx
  on public.activity_group_links(unit_id, status);
create index activity_group_links_profile_idx
  on public.activity_group_links(permission_profile_id)
  where permission_profile_id is not null;
create index activity_group_links_linked_by_idx
  on public.activity_group_links(linked_by_person_id);

create table public.activity_group_assignments (
  id uuid primary key default gen_random_uuid(),
  activity_group_link_id uuid not null,
  institution_id uuid not null,
  person_id uuid not null references public.people(id) on delete cascade,
  membership_id uuid not null,
  assignment_role text not null,
  status public.record_status not null default 'active',
  assigned_by_person_id uuid not null references public.people(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_group_assignments_id_institution_key unique (id, institution_id),
  constraint activity_group_assignments_role_not_blank
    check (btrim(assignment_role) <> ''),
  constraint activity_group_assignments_revocation_check check (
    (status in ('inactive', 'suspended', 'archived') and revoked_at is not null)
    or (status in ('draft', 'active') and revoked_at is null)
  ),
  constraint activity_group_assignments_group_link_fkey
    foreign key (activity_group_link_id, institution_id)
    references public.activity_group_links(id, institution_id)
    on delete cascade,
  constraint activity_group_assignments_membership_fkey
    foreign key (membership_id, institution_id, person_id)
    references public.institution_memberships(id, institution_id, person_id)
    on delete restrict
);

create unique index activity_group_assignments_active_uidx
  on public.activity_group_assignments(
    activity_group_link_id,
    person_id,
    lower(assignment_role)
  )
  where status = 'active' and revoked_at is null;
create index activity_group_assignments_group_status_idx
  on public.activity_group_assignments(activity_group_link_id, status);
create index activity_group_assignments_person_status_idx
  on public.activity_group_assignments(person_id, status);
create index activity_group_assignments_membership_idx
  on public.activity_group_assignments(membership_id);
create index activity_group_assignments_assigned_by_idx
  on public.activity_group_assignments(assigned_by_person_id);

create table public.activity_assignment_permission_overrides (
  id uuid primary key default gen_random_uuid(),
  assignment_id uuid not null references public.activity_group_assignments(id) on delete cascade,
  capability_id uuid not null references public.activity_capabilities(id) on delete restrict,
  effect public.permission_effect not null,
  changed_by_person_id uuid not null references public.people(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assignment_id, capability_id)
);

create index activity_assignment_overrides_capability_idx
  on public.activity_assignment_permission_overrides(capability_id);
create index activity_assignment_overrides_changed_by_idx
  on public.activity_assignment_permission_overrides(changed_by_person_id);

create table public.activity_suggestions (
  id uuid primary key default gen_random_uuid(),
  institution_id uuid not null references public.institutions(id) on delete cascade,
  scope_kind public.activity_permission_scope not null,
  unit_id uuid,
  template_code text not null,
  suggested_name text not null,
  suggested_description text,
  status public.record_status not null default 'active',
  created_by_person_id uuid not null references public.people(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  constraint activity_suggestions_scope_check check (
    (scope_kind = 'institution' and unit_id is null)
    or (scope_kind = 'unit' and unit_id is not null)
  ),
  constraint activity_suggestions_code_not_blank check (btrim(template_code) <> ''),
  constraint activity_suggestions_name_not_blank check (btrim(suggested_name) <> ''),
  constraint activity_suggestions_description_not_blank
    check (suggested_description is null or btrim(suggested_description) <> ''),
  constraint activity_suggestions_archive_check check (
    (status = 'archived' and archived_at is not null)
    or (status <> 'archived' and archived_at is null)
  ),
  constraint activity_suggestions_unit_fkey
    foreign key (unit_id, institution_id)
    references public.units(id, institution_id)
    on delete restrict
);

create unique index activity_suggestions_scope_code_uidx
  on public.activity_suggestions(
    institution_id,
    scope_kind,
    coalesce(unit_id, '00000000-0000-0000-0000-000000000000'::uuid),
    lower(template_code)
  )
  where status <> 'archived';
create index activity_suggestions_institution_status_idx
  on public.activity_suggestions(institution_id, status);
create index activity_suggestions_unit_idx
  on public.activity_suggestions(unit_id)
  where unit_id is not null;
create index activity_suggestions_created_by_idx
  on public.activity_suggestions(created_by_person_id);

insert into public.institution_permissions(
  code,
  module_code,
  screen_code,
  action_code,
  description,
  risk_level,
  requires_mfa
)
values
  ('activities.read', 'activities', 'activities', 'read', 'Ler atividades no escopo institucional autorizado.', 'normal', false),
  ('activities.create', 'activities', 'activities', 'create', 'Criar atividades pela instituicao ou unidade autorizada.', 'normal', false),
  ('activities.manage', 'activities', 'activities', 'manage', 'Editar, inativar e arquivar definicoes de atividade.', 'high', false),
  ('activities.link_units', 'activities', 'units', 'link', 'Vincular atividades a unidades autorizadas.', 'high', false),
  ('activities.link_groups', 'activities', 'groups', 'link', 'Vincular atividades a grupos autorizados.', 'normal', false),
  ('activities.assign_people', 'activities', 'assignments', 'manage', 'Atribuir pessoas a atividades no contexto do grupo.', 'high', false),
  ('activities.manage_permissions', 'activities', 'permissions', 'manage', 'Gerir perfis e overrides de capacidades da atividade.', 'high', false)
on conflict (code) do update set
  module_code = excluded.module_code,
  screen_code = excluded.screen_code,
  action_code = excluded.action_code,
  description = excluded.description,
  risk_level = excluded.risk_level,
  requires_mfa = excluded.requires_mfa,
  status = 'active',
  updated_at = now();

insert into public.activity_capabilities(code, name, description)
values
  ('conversation', 'Conversa', 'Permite participar de conversas no contexto da atividade e turma.'),
  ('attendance', 'Presenca e assiduidade', 'Permite operar presenca e assiduidade no contexto da atividade e turma.'),
  ('events', 'Eventos', 'Permite operar eventos de agenda no contexto da atividade e turma.'),
  ('media_now', 'Midia e Now', 'Permite publicar midia ou Now no contexto da atividade e turma.')
on conflict do nothing;

create or replace function app_private.has_institution_permission(
  target_institution_id uuid,
  target_permission_code text,
  target_unit_id uuid default null,
  target_group_id uuid default null,
  require_institution_scope boolean default false
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  with current_person as (
    select app_private.current_person_id() as person_id
  ),
  active_memberships as (
    select membership.id
    from public.institution_memberships membership
    join current_person on current_person.person_id = membership.person_id
    where membership.institution_id = target_institution_id
      and membership.status = 'active'
      and membership.revoked_at is null
  ),
  applicable_role_permissions as (
    select role_permission.effect
    from active_memberships membership
    join public.institution_role_assignments assignment
      on assignment.membership_id = membership.id
     and assignment.status = 'active'
     and (assignment.starts_at is null or assignment.starts_at <= pg_catalog.now())
     and (assignment.expires_at is null or assignment.expires_at > pg_catalog.now())
    join public.institution_roles role_record
      on role_record.id = assignment.role_id
     and role_record.status = 'active'
     and (
       role_record.institution_id is null
       or role_record.institution_id = target_institution_id
     )
    join public.institution_role_permissions role_permission
      on role_permission.role_id = role_record.id
     and role_permission.status = 'active'
     and role_permission.revoked_at is null
    join public.institution_permissions permission_record
      on permission_record.id = role_permission.permission_id
     and permission_record.code = target_permission_code
     and permission_record.status = 'active'
    where (
      (
        require_institution_scope
        and assignment.scope_kind = 'institution'
      )
      or (
        not require_institution_scope
        and (
          assignment.scope_kind = 'institution'
          or (
            assignment.scope_kind = 'unit'
            and target_unit_id is not null
            and assignment.scope_unit_id = target_unit_id
          )
          or (
            assignment.scope_kind = 'group'
            and target_group_id is not null
            and assignment.scope_group_id = target_group_id
            and (
              target_unit_id is null
              or assignment.scope_unit_id = target_unit_id
            )
          )
        )
      )
    )
  ),
  applicable_direct_grants as (
    select 1
    from active_memberships membership
    join public.institution_role_grants direct_grant
      on direct_grant.membership_id = membership.id
     and direct_grant.permission_code = target_permission_code
     and direct_grant.status = 'active'
     and (direct_grant.starts_at is null or direct_grant.starts_at <= pg_catalog.now())
     and (direct_grant.expires_at is null or direct_grant.expires_at > pg_catalog.now())
    where (
      (
        require_institution_scope
        and direct_grant.scope_kind = 'institution'
      )
      or (
        not require_institution_scope
        and (
          direct_grant.scope_kind = 'institution'
          or (
            direct_grant.scope_kind = 'unit'
            and target_unit_id is not null
            and direct_grant.scope_id = target_unit_id
          )
          or (
            direct_grant.scope_kind = 'group'
            and target_group_id is not null
            and direct_grant.scope_id = target_group_id
          )
        )
      )
    )
  )
  select
    not exists (
      select 1
      from applicable_role_permissions
      where effect = 'deny'
    )
    and (
      exists (
        select 1
        from applicable_role_permissions
        where effect = 'allow'
      )
      or exists (select 1 from applicable_direct_grants)
    )
$$;

create or replace function app_private.has_activity_context_access(
  target_activity_id uuid,
  target_unit_id uuid default null,
  target_group_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.activity_group_assignments assignment
    join public.activity_group_links group_link
      on group_link.id = assignment.activity_group_link_id
     and group_link.institution_id = assignment.institution_id
    join public.activity_definitions activity
      on activity.id = group_link.activity_id
     and activity.institution_id = group_link.institution_id
    where assignment.person_id = app_private.current_person_id()
      and assignment.status = 'active'
      and assignment.revoked_at is null
      and group_link.status = 'active'
      and activity.status = 'active'
      and activity.id = target_activity_id
      and (target_unit_id is null or group_link.unit_id = target_unit_id)
      and (target_group_id is null or group_link.group_id = target_group_id)
  )
$$;

create or replace function app_private.has_activity_capability(
  target_activity_id uuid,
  target_group_id uuid,
  target_capability_code text
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  with current_assignment as (
    select
      assignment.id,
      group_link.permission_profile_id
    from public.activity_group_assignments assignment
    join public.activity_group_links group_link
      on group_link.id = assignment.activity_group_link_id
     and group_link.institution_id = assignment.institution_id
    join public.activity_definitions activity
      on activity.id = group_link.activity_id
     and activity.institution_id = group_link.institution_id
    where assignment.person_id = app_private.current_person_id()
      and assignment.status = 'active'
      and assignment.revoked_at is null
      and group_link.status = 'active'
      and activity.status = 'active'
      and activity.id = target_activity_id
      and group_link.group_id = target_group_id
    limit 1
  ),
  target_capability as (
    select capability.id
    from public.activity_capabilities capability
    where capability.code = target_capability_code
      and capability.status = 'active'
  ),
  assignment_override as (
    select override_record.effect
    from current_assignment assignment
    join public.activity_assignment_permission_overrides override_record
      on override_record.assignment_id = assignment.id
    join target_capability capability
      on capability.id = override_record.capability_id
    limit 1
  ),
  profile_permission as (
    select profile_capability.effect
    from current_assignment assignment
    join public.activity_permission_profile_capabilities profile_capability
      on profile_capability.profile_id = assignment.permission_profile_id
    join target_capability capability
      on capability.id = profile_capability.capability_id
    limit 1
  )
  select case
    when not exists (select 1 from current_assignment) then false
    when exists (
      select 1 from assignment_override where effect = 'deny'
    ) then false
    when exists (
      select 1 from assignment_override where effect = 'allow'
    ) then true
    when exists (
      select 1 from profile_permission where effect = 'allow'
    ) then true
    else false
  end
$$;

create or replace function app_private.set_activity_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := pg_catalog.now();
  return new;
end
$$;

create or replace function app_private.validate_activity_group_profile()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  profile_scope public.activity_permission_scope;
  profile_unit_id uuid;
begin
  if new.permission_profile_id is null then
    return new;
  end if;

  select profile.scope_kind, profile.unit_id
  into profile_scope, profile_unit_id
  from public.activity_permission_profiles profile
  where profile.id = new.permission_profile_id
    and profile.institution_id = new.institution_id;

  if profile_scope = 'unit' and profile_unit_id <> new.unit_id then
    raise check_violation using
      message = 'unit-scoped activity profile must match the activity group unit';
  end if;

  return new;
end
$$;

create or replace function app_private.enforce_activity_active_unit()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_activity_id uuid;
  row_data jsonb;
begin
  row_data := case
    when tg_op = 'DELETE' then to_jsonb(old)
    else to_jsonb(new)
  end;
  target_activity_id := coalesce(
    (row_data ->> 'activity_id')::uuid,
    (row_data ->> 'id')::uuid
  );

  if not exists (
    select 1
    from public.activity_definitions activity
    where activity.id = target_activity_id
  ) then
    return coalesce(new, old);
  end if;

  if not exists (
    select 1
    from public.activity_unit_links unit_link
    where unit_link.activity_id = target_activity_id
      and unit_link.status = 'active'
      and (unit_link.ends_at is null or unit_link.ends_at > pg_catalog.now())
  ) then
    raise check_violation using
      message = 'activity must retain at least one active unit link';
  end if;

  return coalesce(new, old);
end
$$;

create or replace function app_private.audit_activity_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_data jsonb;
  before_data jsonb;
  after_data jsonb;
  target_institution_id uuid;
  target_object_id uuid;
  actor_person_id uuid;
  actor_membership_id uuid;
begin
  before_data := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  after_data := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  row_data := coalesce(after_data, before_data);
  target_object_id := (row_data ->> 'id')::uuid;

  if row_data ? 'institution_id' then
    target_institution_id := (row_data ->> 'institution_id')::uuid;
  elsif tg_table_name = 'activity_permission_profile_capabilities' then
    select profile.institution_id
    into target_institution_id
    from public.activity_permission_profiles profile
    where profile.id = (row_data ->> 'profile_id')::uuid;
  elsif tg_table_name = 'activity_assignment_permission_overrides' then
    select assignment.institution_id
    into target_institution_id
    from public.activity_group_assignments assignment
    where assignment.id = (row_data ->> 'assignment_id')::uuid;
  end if;

  actor_person_id := app_private.current_person_id();

  select membership.id
  into actor_membership_id
  from public.institution_memberships membership
  where membership.person_id = actor_person_id
    and membership.institution_id = target_institution_id
    and membership.status = 'active'
    and membership.revoked_at is null
  limit 1;

  insert into audit.audit_logs(
    actor_person_id,
    actor_membership_id,
    mfa_aal,
    action_code,
    object_type,
    object_id,
    institution_id,
    outcome,
    reason,
    before_json,
    after_json
  ) values (
    actor_person_id,
    actor_membership_id,
    auth.jwt() ->> 'aal',
    'activity_' || lower(tg_op),
    tg_table_name,
    target_object_id,
    target_institution_id,
    'success',
    nullif(current_setting('coelo.audit_reason', true), ''),
    before_data,
    after_data
  );

  return coalesce(new, old);
end
$$;

create or replace function app_private.create_activity_for_institution(
  target_institution_id uuid,
  initial_unit_id uuid,
  activity_name text,
  activity_description text default null,
  audit_reason text default null
)
returns public.activity_definitions
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_person_id uuid;
  created_activity public.activity_definitions;
begin
  actor_person_id := app_private.current_person_id();

  if auth.uid() is null or actor_person_id is null then
    raise insufficient_privilege using message = 'authenticated person is required';
  end if;

  if btrim(coalesce(activity_name, '')) = '' then
    raise check_violation using message = 'activity name is required';
  end if;

  if not exists (
    select 1
    from public.units unit_record
    where unit_record.id = initial_unit_id
      and unit_record.institution_id = target_institution_id
      and unit_record.status = 'active'
  ) then
    raise foreign_key_violation using
      message = 'initial unit must be active and belong to the institution';
  end if;

  if not app_private.has_institution_permission(
    target_institution_id,
    'activities.create',
    initial_unit_id,
    null,
    true
  ) then
    raise insufficient_privilege using
      message = 'activities.create at institution scope is required';
  end if;

  perform set_config('coelo.audit_reason', coalesce(audit_reason, ''), true);

  insert into public.activity_definitions(
    institution_id,
    name,
    description,
    origin_scope_kind,
    created_by_person_id
  ) values (
    target_institution_id,
    btrim(activity_name),
    nullif(btrim(coalesce(activity_description, '')), ''),
    'institution',
    actor_person_id
  )
  returning * into created_activity;

  insert into public.activity_unit_links(
    activity_id,
    institution_id,
    unit_id,
    linked_by_person_id
  ) values (
    created_activity.id,
    target_institution_id,
    initial_unit_id,
    actor_person_id
  );

  return created_activity;
end
$$;

create or replace function app_private.create_activity_for_unit(
  origin_unit_id uuid,
  activity_name text,
  activity_description text default null,
  audit_reason text default null
)
returns public.activity_definitions
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_person_id uuid;
  derived_institution_id uuid;
  created_activity public.activity_definitions;
begin
  actor_person_id := app_private.current_person_id();

  if auth.uid() is null or actor_person_id is null then
    raise insufficient_privilege using message = 'authenticated person is required';
  end if;

  if btrim(coalesce(activity_name, '')) = '' then
    raise check_violation using message = 'activity name is required';
  end if;

  select unit_record.institution_id
  into derived_institution_id
  from public.units unit_record
  where unit_record.id = origin_unit_id
    and unit_record.status = 'active';

  if derived_institution_id is null then
    raise foreign_key_violation using message = 'active origin unit is required';
  end if;

  if not app_private.has_institution_permission(
    derived_institution_id,
    'activities.create',
    origin_unit_id,
    null,
    false
  ) then
    raise insufficient_privilege using
      message = 'activities.create for the origin unit is required';
  end if;

  perform set_config('coelo.audit_reason', coalesce(audit_reason, ''), true);

  insert into public.activity_definitions(
    institution_id,
    name,
    description,
    origin_scope_kind,
    origin_unit_id,
    created_by_person_id
  ) values (
    derived_institution_id,
    btrim(activity_name),
    nullif(btrim(coalesce(activity_description, '')), ''),
    'unit',
    origin_unit_id,
    actor_person_id
  )
  returning * into created_activity;

  insert into public.activity_unit_links(
    activity_id,
    institution_id,
    unit_id,
    linked_by_person_id
  ) values (
    created_activity.id,
    derived_institution_id,
    origin_unit_id,
    actor_person_id
  );

  return created_activity;
end
$$;

create or replace function public.create_activity_for_institution(
  target_institution_id uuid,
  initial_unit_id uuid,
  activity_name text,
  activity_description text default null,
  audit_reason text default null
)
returns public.activity_definitions
language sql
volatile
security invoker
set search_path = ''
as $$
  select app_private.create_activity_for_institution(
    target_institution_id,
    initial_unit_id,
    activity_name,
    activity_description,
    audit_reason
  )
$$;

create or replace function public.create_activity_for_unit(
  origin_unit_id uuid,
  activity_name text,
  activity_description text default null,
  audit_reason text default null
)
returns public.activity_definitions
language sql
volatile
security invoker
set search_path = ''
as $$
  select app_private.create_activity_for_unit(
    origin_unit_id,
    activity_name,
    activity_description,
    audit_reason
  )
$$;

revoke all on function app_private.has_institution_permission(uuid, text, uuid, uuid, boolean)
  from public, anon;
revoke all on function app_private.has_activity_context_access(uuid, uuid, uuid)
  from public, anon;
revoke all on function app_private.has_activity_capability(uuid, uuid, text)
  from public, anon;
revoke all on function app_private.create_activity_for_institution(uuid, uuid, text, text, text)
  from public, anon;
revoke all on function app_private.create_activity_for_unit(uuid, text, text, text)
  from public, anon;
revoke all on function public.create_activity_for_institution(uuid, uuid, text, text, text)
  from public, anon;
revoke all on function public.create_activity_for_unit(uuid, text, text, text)
  from public, anon;

grant execute on function app_private.has_institution_permission(uuid, text, uuid, uuid, boolean)
  to authenticated;
grant execute on function app_private.has_activity_context_access(uuid, uuid, uuid)
  to authenticated;
grant execute on function app_private.has_activity_capability(uuid, uuid, text)
  to authenticated;
grant execute on function app_private.create_activity_for_institution(uuid, uuid, text, text, text)
  to authenticated;
grant execute on function app_private.create_activity_for_unit(uuid, text, text, text)
  to authenticated;
grant execute on function public.create_activity_for_institution(uuid, uuid, text, text, text)
  to authenticated;
grant execute on function public.create_activity_for_unit(uuid, text, text, text)
  to authenticated;

revoke all on function app_private.set_activity_updated_at() from public, anon, authenticated;
revoke all on function app_private.validate_activity_group_profile() from public, anon, authenticated;
revoke all on function app_private.enforce_activity_active_unit() from public, anon, authenticated;
revoke all on function app_private.audit_activity_change() from public, anon, authenticated;

create trigger activity_definitions_updated_at
before update on public.activity_definitions
for each row execute function app_private.set_activity_updated_at();
create trigger activity_unit_links_updated_at
before update on public.activity_unit_links
for each row execute function app_private.set_activity_updated_at();
create trigger activity_permission_profiles_updated_at
before update on public.activity_permission_profiles
for each row execute function app_private.set_activity_updated_at();
create trigger activity_permission_profile_capabilities_updated_at
before update on public.activity_permission_profile_capabilities
for each row execute function app_private.set_activity_updated_at();
create trigger activity_group_links_updated_at
before update on public.activity_group_links
for each row execute function app_private.set_activity_updated_at();
create trigger activity_group_assignments_updated_at
before update on public.activity_group_assignments
for each row execute function app_private.set_activity_updated_at();
create trigger activity_assignment_permission_overrides_updated_at
before update on public.activity_assignment_permission_overrides
for each row execute function app_private.set_activity_updated_at();
create trigger activity_suggestions_updated_at
before update on public.activity_suggestions
for each row execute function app_private.set_activity_updated_at();

create trigger activity_group_links_validate_profile
before insert or update of permission_profile_id, institution_id, unit_id
on public.activity_group_links
for each row execute function app_private.validate_activity_group_profile();

create constraint trigger activity_definition_requires_unit
after insert or update on public.activity_definitions
deferrable initially deferred
for each row execute function app_private.enforce_activity_active_unit();

create constraint trigger activity_unit_links_retain_one
after insert or update or delete on public.activity_unit_links
deferrable initially deferred
for each row execute function app_private.enforce_activity_active_unit();

create trigger activity_definitions_audit
after insert or update or delete on public.activity_definitions
for each row execute function app_private.audit_activity_change();
create trigger activity_unit_links_audit
after insert or update or delete on public.activity_unit_links
for each row execute function app_private.audit_activity_change();
create trigger activity_permission_profiles_audit
after insert or update or delete on public.activity_permission_profiles
for each row execute function app_private.audit_activity_change();
create trigger activity_permission_profile_capabilities_audit
after insert or update or delete on public.activity_permission_profile_capabilities
for each row execute function app_private.audit_activity_change();
create trigger activity_group_links_audit
after insert or update or delete on public.activity_group_links
for each row execute function app_private.audit_activity_change();
create trigger activity_group_assignments_audit
after insert or update or delete on public.activity_group_assignments
for each row execute function app_private.audit_activity_change();
create trigger activity_assignment_permission_overrides_audit
after insert or update or delete on public.activity_assignment_permission_overrides
for each row execute function app_private.audit_activity_change();
create trigger activity_suggestions_audit
after insert or update or delete on public.activity_suggestions
for each row execute function app_private.audit_activity_change();

do $$
declare
  current_table text;
begin
  foreach current_table in array array[
    'activity_capabilities',
    'activity_definitions',
    'activity_unit_links',
    'activity_permission_profiles',
    'activity_permission_profile_capabilities',
    'activity_group_links',
    'activity_group_assignments',
    'activity_assignment_permission_overrides',
    'activity_suggestions'
  ]
  loop
    execute format('alter table public.%I enable row level security', current_table);
    execute format(
      'revoke all on table public.%I from public, anon, authenticated',
      current_table
    );
    execute format(
      'grant all on table public.%I to service_role',
      current_table
    );
  end loop;
end
$$;

grant select on public.activity_capabilities to authenticated;
grant select, update on public.activity_definitions to authenticated;
grant select, insert, update on public.activity_unit_links to authenticated;
grant select, insert, update on public.activity_permission_profiles to authenticated;
grant select, insert, update, delete
  on public.activity_permission_profile_capabilities to authenticated;
grant select, insert, update on public.activity_group_links to authenticated;
grant select, insert, update on public.activity_group_assignments to authenticated;
grant select, insert, update, delete
  on public.activity_assignment_permission_overrides to authenticated;
grant select, insert, update on public.activity_suggestions to authenticated;

create policy activity_capabilities_authenticated_read
on public.activity_capabilities
for select
to authenticated
using ((select auth.uid()) is not null);

create policy activity_definitions_context_read
on public.activity_definitions
for select
to authenticated
using (
  (select app_private.has_platform_permission('platform.read'))
  or app_private.has_activity_context_access(id, null, null)
  or exists (
    select 1
    from public.activity_unit_links unit_link
    where unit_link.activity_id = activity_definitions.id
      and unit_link.status = 'active'
      and app_private.has_institution_permission(
        activity_definitions.institution_id,
        'activities.read',
        unit_link.unit_id,
        null,
        false
      )
  )
);

create policy activity_definitions_institution_update
on public.activity_definitions
for update
to authenticated
using (
  app_private.has_institution_permission(
    institution_id,
    'activities.manage',
    null,
    null,
    true
  )
)
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.manage',
    null,
    null,
    true
  )
);

create policy activity_unit_links_context_read
on public.activity_unit_links
for select
to authenticated
using (
  (select app_private.has_platform_permission('platform.read'))
  or app_private.has_activity_context_access(activity_id, unit_id, null)
  or app_private.has_institution_permission(
    institution_id,
    'activities.read',
    unit_id,
    null,
    false
  )
);

create policy activity_unit_links_authorized_insert
on public.activity_unit_links
for insert
to authenticated
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.link_units',
    unit_id,
    null,
    false
  )
);

create policy activity_unit_links_authorized_update
on public.activity_unit_links
for update
to authenticated
using (
  app_private.has_institution_permission(
    institution_id,
    'activities.link_units',
    unit_id,
    null,
    false
  )
)
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.link_units',
    unit_id,
    null,
    false
  )
);

create policy activity_permission_profiles_context_read
on public.activity_permission_profiles
for select
to authenticated
using (
  (select app_private.has_platform_permission('platform.read'))
  or app_private.has_institution_permission(
    institution_id,
    'activities.read',
    unit_id,
    null,
    scope_kind = 'institution'
  )
  or exists (
    select 1
    from public.activity_group_links group_link
    where group_link.permission_profile_id = activity_permission_profiles.id
      and app_private.has_activity_context_access(
        group_link.activity_id,
        group_link.unit_id,
        group_link.group_id
      )
  )
);

create policy activity_permission_profiles_authorized_insert
on public.activity_permission_profiles
for insert
to authenticated
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.manage_permissions',
    unit_id,
    null,
    scope_kind = 'institution'
  )
);

create policy activity_permission_profiles_authorized_update
on public.activity_permission_profiles
for update
to authenticated
using (
  app_private.has_institution_permission(
    institution_id,
    'activities.manage_permissions',
    unit_id,
    null,
    scope_kind = 'institution'
  )
)
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.manage_permissions',
    unit_id,
    null,
    scope_kind = 'institution'
  )
);

create policy activity_profile_capabilities_context_read
on public.activity_permission_profile_capabilities
for select
to authenticated
using (
  exists (
    select 1
    from public.activity_permission_profiles profile
    where profile.id = activity_permission_profile_capabilities.profile_id
  )
);

create policy activity_profile_capabilities_authorized_insert
on public.activity_permission_profile_capabilities
for insert
to authenticated
with check (
  exists (
    select 1
    from public.activity_permission_profiles profile
    where profile.id = activity_permission_profile_capabilities.profile_id
      and app_private.has_institution_permission(
        profile.institution_id,
        'activities.manage_permissions',
        profile.unit_id,
        null,
        profile.scope_kind = 'institution'
      )
  )
);

create policy activity_profile_capabilities_authorized_update
on public.activity_permission_profile_capabilities
for update
to authenticated
using (
  exists (
    select 1
    from public.activity_permission_profiles profile
    where profile.id = activity_permission_profile_capabilities.profile_id
      and app_private.has_institution_permission(
        profile.institution_id,
        'activities.manage_permissions',
        profile.unit_id,
        null,
        profile.scope_kind = 'institution'
      )
  )
)
with check (
  exists (
    select 1
    from public.activity_permission_profiles profile
    where profile.id = activity_permission_profile_capabilities.profile_id
      and app_private.has_institution_permission(
        profile.institution_id,
        'activities.manage_permissions',
        profile.unit_id,
        null,
        profile.scope_kind = 'institution'
      )
  )
);

create policy activity_profile_capabilities_authorized_delete
on public.activity_permission_profile_capabilities
for delete
to authenticated
using (
  exists (
    select 1
    from public.activity_permission_profiles profile
    where profile.id = activity_permission_profile_capabilities.profile_id
      and app_private.has_institution_permission(
        profile.institution_id,
        'activities.manage_permissions',
        profile.unit_id,
        null,
        profile.scope_kind = 'institution'
      )
  )
);

create policy activity_group_links_context_read
on public.activity_group_links
for select
to authenticated
using (
  (select app_private.has_platform_permission('platform.read'))
  or app_private.has_activity_context_access(activity_id, unit_id, group_id)
  or app_private.has_institution_permission(
    institution_id,
    'activities.read',
    unit_id,
    group_id,
    false
  )
);

create policy activity_group_links_authorized_insert
on public.activity_group_links
for insert
to authenticated
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.link_groups',
    unit_id,
    group_id,
    false
  )
);

create policy activity_group_links_authorized_update
on public.activity_group_links
for update
to authenticated
using (
  app_private.has_institution_permission(
    institution_id,
    'activities.link_groups',
    unit_id,
    group_id,
    false
  )
)
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.link_groups',
    unit_id,
    group_id,
    false
  )
);

create policy activity_group_assignments_context_read
on public.activity_group_assignments
for select
to authenticated
using (
  (select app_private.has_platform_permission('platform.read'))
  or person_id = app_private.current_person_id()
  or exists (
    select 1
    from public.activity_group_links group_link
    where group_link.id = activity_group_assignments.activity_group_link_id
      and app_private.has_institution_permission(
        activity_group_assignments.institution_id,
        'activities.read',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
);

create policy activity_group_assignments_authorized_insert
on public.activity_group_assignments
for insert
to authenticated
with check (
  exists (
    select 1
    from public.activity_group_links group_link
    where group_link.id = activity_group_assignments.activity_group_link_id
      and group_link.institution_id = activity_group_assignments.institution_id
      and app_private.has_institution_permission(
        activity_group_assignments.institution_id,
        'activities.assign_people',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
);

create policy activity_group_assignments_authorized_update
on public.activity_group_assignments
for update
to authenticated
using (
  exists (
    select 1
    from public.activity_group_links group_link
    where group_link.id = activity_group_assignments.activity_group_link_id
      and app_private.has_institution_permission(
        activity_group_assignments.institution_id,
        'activities.assign_people',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
)
with check (
  exists (
    select 1
    from public.activity_group_links group_link
    where group_link.id = activity_group_assignments.activity_group_link_id
      and group_link.institution_id = activity_group_assignments.institution_id
      and app_private.has_institution_permission(
        activity_group_assignments.institution_id,
        'activities.assign_people',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
);

create policy activity_assignment_overrides_context_read
on public.activity_assignment_permission_overrides
for select
to authenticated
using (
  exists (
    select 1
    from public.activity_group_assignments assignment
    where assignment.id = activity_assignment_permission_overrides.assignment_id
      and (
        assignment.person_id = app_private.current_person_id()
        or exists (
          select 1
          from public.activity_group_links group_link
          where group_link.id = assignment.activity_group_link_id
            and app_private.has_institution_permission(
              assignment.institution_id,
              'activities.read',
              group_link.unit_id,
              group_link.group_id,
              false
            )
        )
      )
  )
);

create policy activity_assignment_overrides_authorized_insert
on public.activity_assignment_permission_overrides
for insert
to authenticated
with check (
  exists (
    select 1
    from public.activity_group_assignments assignment
    join public.activity_group_links group_link
      on group_link.id = assignment.activity_group_link_id
    where assignment.id = activity_assignment_permission_overrides.assignment_id
      and app_private.has_institution_permission(
        assignment.institution_id,
        'activities.manage_permissions',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
);

create policy activity_assignment_overrides_authorized_update
on public.activity_assignment_permission_overrides
for update
to authenticated
using (
  exists (
    select 1
    from public.activity_group_assignments assignment
    join public.activity_group_links group_link
      on group_link.id = assignment.activity_group_link_id
    where assignment.id = activity_assignment_permission_overrides.assignment_id
      and app_private.has_institution_permission(
        assignment.institution_id,
        'activities.manage_permissions',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
)
with check (
  exists (
    select 1
    from public.activity_group_assignments assignment
    join public.activity_group_links group_link
      on group_link.id = assignment.activity_group_link_id
    where assignment.id = activity_assignment_permission_overrides.assignment_id
      and app_private.has_institution_permission(
        assignment.institution_id,
        'activities.manage_permissions',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
);

create policy activity_assignment_overrides_authorized_delete
on public.activity_assignment_permission_overrides
for delete
to authenticated
using (
  exists (
    select 1
    from public.activity_group_assignments assignment
    join public.activity_group_links group_link
      on group_link.id = assignment.activity_group_link_id
    where assignment.id = activity_assignment_permission_overrides.assignment_id
      and app_private.has_institution_permission(
        assignment.institution_id,
        'activities.manage_permissions',
        group_link.unit_id,
        group_link.group_id,
        false
      )
  )
);

create policy activity_suggestions_context_read
on public.activity_suggestions
for select
to authenticated
using (
  (select app_private.has_platform_permission('platform.read'))
  or app_private.has_institution_permission(
    institution_id,
    'activities.read',
    unit_id,
    null,
    scope_kind = 'institution'
  )
);

create policy activity_suggestions_authorized_insert
on public.activity_suggestions
for insert
to authenticated
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.create',
    unit_id,
    null,
    scope_kind = 'institution'
  )
);

create policy activity_suggestions_authorized_update
on public.activity_suggestions
for update
to authenticated
using (
  app_private.has_institution_permission(
    institution_id,
    'activities.create',
    unit_id,
    null,
    scope_kind = 'institution'
  )
)
with check (
  app_private.has_institution_permission(
    institution_id,
    'activities.create',
    unit_id,
    null,
    scope_kind = 'institution'
  )
);

with table_catalog(table_name, table_label, table_description) as (
  values
    ('activity_definitions', 'Atividades', 'Definicoes reutilizaveis de atividade pertencentes a uma instituicao.'),
    ('activity_unit_links', 'Atividades por unidade', 'Disponibilidade e vinculo obrigatorio de atividades com unidades.'),
    ('activity_group_links', 'Atividades por turma', 'Atividade aplicada no contexto de um grupo ou turma.'),
    ('activity_group_assignments', 'Pessoas por atividade e turma', 'Pessoas atribuidas a uma atividade dentro de uma turma.'),
    ('activity_capabilities', 'Capacidades de atividade', 'Catalogo de capacidades operacionais contextualizadas pela atividade.'),
    ('activity_permission_profiles', 'Perfis de permissao de atividade', 'Perfis reutilizaveis de capacidades por instituicao ou unidade.'),
    ('activity_permission_profile_capabilities', 'Capacidades por perfil de atividade', 'Capacidades liberadas ou negadas por perfil de atividade.'),
    ('activity_assignment_permission_overrides', 'Overrides por atribuicao de atividade', 'Excecoes de capacidade por pessoa, atividade e turma.'),
    ('activity_suggestions', 'Sugestoes de atividades', 'Sugestoes editaveis pertencentes a instituicao ou unidade.')
)
insert into public.schema_tables(
  schema_name,
  table_name,
  table_label,
  table_description,
  domain,
  status,
  version,
  updated_at
)
select
  'public',
  table_catalog.table_name,
  table_catalog.table_label,
  table_catalog.table_description,
  'activities',
  'active',
  1,
  now()
from table_catalog
on conflict (schema_name, table_name, version) do update set
  table_label = excluded.table_label,
  table_description = excluded.table_description,
  domain = excluded.domain,
  status = 'active',
  updated_at = now();

insert into public.schema_columns(
  schema_table_id,
  column_name,
  column_label,
  column_description,
  column_type,
  is_required,
  is_nullable,
  is_unique,
  is_filterable,
  is_importable,
  is_active,
  position,
  allowed_locales_json,
  aliases_json,
  examples_json,
  updated_at
)
select
  schema_table.id,
  column_info.column_name,
  case column_info.column_name
    when 'id' then 'ID'
    when 'activity_id' then 'Atividade'
    when 'activity_group_link_id' then 'Atividade na turma'
    when 'assignment_id' then 'Atribuicao'
    when 'capability_id' then 'Capacidade'
    when 'profile_id' then 'Perfil de permissao'
    when 'permission_profile_id' then 'Perfil de permissao'
    when 'institution_id' then 'Instituicao'
    when 'unit_id' then 'Unidade'
    when 'group_id' then 'Grupo'
    when 'person_id' then 'Pessoa'
    when 'membership_id' then 'Vinculo institucional'
    when 'name' then 'Nome'
    when 'code' then 'Codigo'
    when 'description' then 'Descricao'
    when 'status' then 'Status'
    when 'created_at' then 'Criado em'
    when 'updated_at' then 'Atualizado em'
    else initcap(replace(column_info.column_name, '_', ' '))
  end,
  'Campo ' || column_info.column_name || ' da tabela ' || schema_table.table_label || '.',
  case
    when column_info.data_type = 'USER-DEFINED'
      then column_info.udt_schema || '.' || column_info.udt_name
    else column_info.data_type
  end,
  column_info.is_nullable = 'NO' and column_info.column_default is null,
  column_info.is_nullable = 'YES',
  false,
  (
    column_info.column_name = 'id'
    or column_info.column_name like '%\_id' escape '\'
    or column_info.column_name in (
      'code',
      'template_code',
      'status',
      'scope_kind',
      'origin_scope_kind',
      'assignment_role'
    )
    or column_info.column_name like '%\_at' escape '\'
  ),
  column_info.table_name in (
    'activity_definitions',
    'activity_unit_links',
    'activity_group_links',
    'activity_group_assignments',
    'activity_suggestions'
  ),
  true,
  column_info.ordinal_position,
  '["pt-BR"]'::jsonb,
  '{}'::jsonb,
  '[]'::jsonb,
  now()
from information_schema.columns column_info
join public.schema_tables schema_table
  on schema_table.schema_name = column_info.table_schema
 and schema_table.table_name = column_info.table_name
 and schema_table.version = 1
where column_info.table_schema = 'public'
  and column_info.table_name in (
    'activity_definitions',
    'activity_unit_links',
    'activity_group_links',
    'activity_group_assignments',
    'activity_capabilities',
    'activity_permission_profiles',
    'activity_permission_profile_capabilities',
    'activity_assignment_permission_overrides',
    'activity_suggestions'
  )
on conflict (schema_table_id, column_name) do update set
  column_label = excluded.column_label,
  column_description = excluded.column_description,
  column_type = excluded.column_type,
  is_required = excluded.is_required,
  is_nullable = excluded.is_nullable,
  is_filterable = excluded.is_filterable,
  is_importable = excluded.is_importable,
  is_active = true,
  position = excluded.position,
  updated_at = now();
