-- Timestamp generated by the official Supabase CLI:
-- supabase migration new contextual_activities_fk_index_hardening

create index activity_definitions_origin_unit_institution_idx
  on public.activity_definitions(origin_unit_id, institution_id);

create index activity_unit_links_unit_institution_idx
  on public.activity_unit_links(unit_id, institution_id);

create index activity_permission_profiles_unit_institution_idx
  on public.activity_permission_profiles(unit_id, institution_id);

create index activity_group_links_activity_institution_unit_idx
  on public.activity_group_links(activity_id, institution_id, unit_id);

create index activity_group_links_group_institution_unit_idx
  on public.activity_group_links(group_id, institution_id, unit_id);

create index activity_group_links_profile_institution_idx
  on public.activity_group_links(permission_profile_id, institution_id);

create index activity_group_assignments_link_institution_idx
  on public.activity_group_assignments(activity_group_link_id, institution_id);

create index activity_group_assignments_membership_institution_person_idx
  on public.activity_group_assignments(membership_id, institution_id, person_id);

create index activity_suggestions_unit_institution_idx
  on public.activity_suggestions(unit_id, institution_id);
