import 'chat_models.dart';

const _messages = [
  SuperadminChatMessage(
    id: 'message-1',
    author: 'Marina · Professora',
    context: 'Turma Girassol · Lia',
    body: 'A atividade terminou e correu tudo bem.',
    time: '10:32',
    sentByMe: false,
  ),
  SuperadminChatMessage(
    id: 'message-2',
    author: 'Superadmin',
    context: 'Contexto histórico · Lia',
    body: 'Obrigada. A família já foi avisada.',
    time: '10:34',
    sentByMe: true,
    delivery: ChatDeliveryState.read,
  ),
  SuperadminChatMessage(
    id: 'message-3',
    author: 'Marina · Professora',
    context: 'Turma Girassol',
    body: 'Perfeito. Também compartilhei o registro da atividade com os responsáveis.',
    time: '10:36',
    sentByMe: false,
  ),
  SuperadminChatMessage(
    id: 'message-4',
    author: 'Superadmin',
    context: 'Turma Girassol',
    body: 'Ótimo. O registro ficará disponível para acompanhamento da instituição.',
    time: '10:40',
    sentByMe: true,
    delivery: ChatDeliveryState.read,
  ),
  SuperadminChatMessage(
    id: 'message-5',
    author: 'Marina · Professora',
    context: 'Turma Girassol',
    body: 'Combinado. Se houver alguma atualização, aviso por aqui.',
    time: '10:42',
    sentByMe: false,
  ),
  SuperadminChatMessage(
    id: 'message-6',
    author: 'Superadmin',
    context: 'Demonstração local',
    body: 'Obrigada, Marina.',
    time: '10:43',
    sentByMe: true,
    delivery: ChatDeliveryState.delivered,
  ),
];

const superadminChatConversations = [
  SuperadminChatConversation(
    id: 'girassol',
    title: 'Turma Girassol',
    initials: 'TG',
    preview: 'Marina enviou uma mensagem.',
    timestamp: '2 min',
    context: 'Centro Horizonte · Unidade Cambuí',
    institution: 'Centro Horizonte',
    kind: ChatContextKind.group,
    metrics: [
      SuperadminChatMetric('Professores', 3),
      SuperadminChatMetric('Crianças', 18),
      SuperadminChatMetric('Responsáveis', 27),
      SuperadminChatMetric('Atividades', 4),
    ],
    messages: _messages,
    state: 'CE',
    role: 'Professores',
    unit: 'Unidade Cambuí',
    group: 'Turma Girassol',
    unreadCount: 3,
    isGroup: true,
  ),
  SuperadminChatConversation(
    id: 'cambui',
    title: 'Unidade Cambuí',
    initials: 'UC',
    preview: 'Documento recebido.',
    timestamp: '1 h',
    context: 'Centro Horizonte',
    institution: 'Centro Horizonte',
    kind: ChatContextKind.unit,
    metrics: [
      SuperadminChatMetric('Grupos', 8),
      SuperadminChatMetric('Funcionários', 34),
      SuperadminChatMetric('Crianças', 126),
    ],
    messages: _messages,
    state: 'CE',
    role: 'Outros',
    unit: 'Unidade Cambuí',
  ),
  SuperadminChatConversation(
    id: 'natacao',
    title: 'Atividade Natação',
    initials: 'AN',
    preview: 'A atividade começa às 16h.',
    timestamp: 'Ontem',
    context: 'Turma Girassol · Lia',
    institution: 'Centro Horizonte',
    kind: ChatContextKind.activity,
    metrics: [
      SuperadminChatMetric('Turmas', 2),
      SuperadminChatMetric('Crianças', 14),
      SuperadminChatMetric('Responsáveis', 20),
    ],
    messages: _messages,
    state: 'CE',
    role: 'Responsáveis',
    unit: 'Unidade Cambuí',
    group: 'Turma Girassol',
  ),
  SuperadminChatConversation(
    id: 'marina',
    title: 'Marina Alves',
    initials: 'MA',
    preview: 'Obrigada pelo retorno.',
    timestamp: '3 h',
    context: 'Professora · Turma Girassol',
    institution: 'Centro Horizonte',
    kind: ChatContextKind.person,
    metrics: [
      SuperadminChatMetric('Instituições', 1),
      SuperadminChatMetric('Turmas', 2),
      SuperadminChatMetric('Crianças', 18),
    ],
    messages: _messages,
    state: 'CE',
    role: 'Professores',
    unit: 'Unidade Cambuí',
    group: 'Turma Girassol',
  ),
  SuperadminChatConversation(
    id: 'aurora',
    title: 'Instituto Aurora',
    initials: 'IA',
    preview: 'A coordenação enviou um aviso.',
    timestamp: '2 d',
    context: 'Unidade Jardins',
    institution: 'Instituto Aurora',
    kind: ChatContextKind.institution,
    metrics: [
      SuperadminChatMetric('Unidades', 3),
      SuperadminChatMetric('Grupos', 14),
      SuperadminChatMetric('Pessoas', 284),
    ],
    messages: _messages,
    state: 'SP',
    unit: 'Unidade Jardins',
  ),
];

const superadminChatContextOptions = [
  SuperadminChatContextOption(
    id: 'centro-horizonte',
    label: 'Centro Horizonte',
    kind: ChatContextKind.institution,
    subtitle: 'Instituição ativa',
    children: [
      SuperadminChatContextOption(
        id: 'cambui',
        label: 'Unidade Cambuí',
        kind: ChatContextKind.unit,
        children: [
          SuperadminChatContextOption(
            id: 'girassol',
            label: 'Turma Girassol',
            kind: ChatContextKind.group,
          ),
        ],
      ),
    ],
  ),
];
