name: coelo_superadmin
description: Aplicacao Flutter privada para operacao interna Coelo.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  coelo_auth:
    path: ../../packages/coelo_auth
  coelo_tokens:
    path: ../../packages/coelo_tokens
  flutter:
    sdk: flutter
  flutter_svg: 2.2.3
  flutter_web_plugins:
    sdk: flutter
  go_router: ^16.0.0
  supabase_flutter: 2.16.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand/logo-coelo-white.svg
    - assets/brand/logo-coelo-orange.svg
    - assets/brand/logo-coelo-orange.png
    - assets/brand/logo-coelo-orange-complete.png
  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/brand/NunitoSans-VariableFont.ttf
